# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Huang Zhenyu
email: zyhuang.gm@gmail.com
description: > # this means to ignore newlines until "url:"
  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: >

url:  # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/
last_updated: 2021.06.23 # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: hi-zhenyu # your GitHub user name
twitter_username: # your Twitter handle
linkedin_username: # your LinkedIn user name
scholar_userid: 0mdxlb8AAAAJ # your Google Scholar ID
orcid_id: 0000-0003-4161-9427 # your ORCID ID
contact_note: >
  Feel free to drop me an email.

google_analytics: UA-127168403-1 # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: AI F H
blog_description: A simple blog.

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 10

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Huang

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
